pose0: icp_pose/monitored
pose0_differential: false
pose0_config: [
    true, true, true,
    true, true, true,
    false, false, false,  
    false, false, false,
    false, false, false
]

odom0: odometry/gps
odom0_differential: false
odom0_config: [
    true, true, true,
    false, false, false,
    false,  false,  false,
    false, false, false,
    false, false, false
]

odom1: odom/monitored
odom1_differential: false
odom1_config: [
    false, false, false,
    false, false, false,
    true,  true,  true,
    true, true, true,
    false, false, false
]

imu0: imu/monitored
imu0_differential: false
imu0_config: [
    false, false, false,
    false,  false,  false,
    false, false, false,
    true,  true,  true,
    false, false, false
]

imu0_remove_gravitational_acceleration: true

initial_state: [
    0, 0, 0,
    0, 0, -0.785398,
    0, 0, 0,
    0, 0, 0,
    0, 0, 0
]

# initial_state: [
#     0, 0, 0,
#     0, 0, -2.2,
#     0, 0, 0,
#     0, 0, 0,
#     0, 0, 0
# ]